apiVersion: v1
kind: Pod
metadata:
  name: pod1
spec:
  containers:
    - name: test-container
      image: gcr.io/google-samples/node-hello:1.0
      envFrom:
      - configMapRef:
          name: datos-mysql
      - configMapRef:
          name: mis-datos
      env:
      - name: Hola
        value: 'Holas'
  restartPolicy: Never
