apiVersion: v1
kind: Pod
metadata:
  name: tomcat
  labels:
    app: tomcat
    appVersion: v1
    env: dev
spec:
  containers:
	- name: tomcat
		image: tomcat:8.0
		ports:
		- containerPort: 8080
		volumeMounts:
		- name: tomcat-vol
			mountPath: /usr/local/tomcat/webapps
  
  restartPolicy: OnFailure