name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]
  
  # Para que pueda ser ejecutado manualmente
  workflow_dispatch:

jobs:

  build:
  
    env:
      platform: github

      username: ${{ secrets.USERNAME }}
      password: ${{ secrets.PASSWORD }}

    runs-on: ubuntu-latest

    steps:
    # - uses: actions/checkout@v3
    # - name: Build the Docker image
    #   run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    - name: "Mostrar mensaje"
      run: echo "Hello Wordls"
            
    - name: "Mostrar variables de entorno"
      # if: ${{ env.platform == 'azure' }}
      run: |
        echo "Mostrando variable platform: ${{ env.platform }}" 
        echo "Mostrando secreto username: ${{ env.username }}" 
        echo "Mostrando secreto password: ${{ env.password }}" 

    - name: "Mostrar variables de entorno globales"
      run: |
        echo "Mostrando evento: ${{ toJson(github.event) }}" 
        echo "Mostrando Github_actor: $GITHUB_ACTOR" 
        echo "Mostrando Github_repository: $GITHUB_REPOSITORY" 